# -*- coding: utf-8 -*-
"""Weather Forecast.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vHekQ9b0oLHIzfHS8dUvsJY8l8Fes1qn
"""

#importing necessary packages
import requests
import os
import time

from bs4 import BeautifulSoup
from datetime import date
from datetime import datetime

def todays_weather():
  #scraping the weather page
  page = 'https://weather.com/weather/today/l/3642fe8520406b7b57aa04bc121b5bbecb32537a62a9d0d6ac727cc8d27e977c'
  req = requests.get(page)
  soup = BeautifulSoup(req.content, 'html.parser')

  #getting todays date
  today = date.today()
  # format:dd/mm/YY
  date_today = today.strftime('%d/%m/%Y')

  #displaying the weather
  pred_phrase = ''

  current_temp = soup.find(class_='CurrentConditions--tempValue--MHmYY').text
  phrase = soup.find(class_='CurrentConditions--phraseValue--mZC_p').text
  temp_hi_lo = soup.find(class_='CurrentConditions--tempHiLoValue--3T1DG').text
  

  if (soup.find(class_='CurrentConditions--precipValue--RBVJT')):
    pred_phrase = soup.find(class_="CurrentConditions--precipValue--RBVJT").text
  

  #displaying icons
  if (phrase == 'Cloudy' or phrase == 'Mostly Cloudy'):
    emoji = '☁️'
  elif (phrase == 'Rain' or phrase == 'Light Rain'):
    emoji = '🌧️'
  elif (phrase == 'Partly Cloudy'):
    emoji = '⛅'
  else:
    emoji = '☀️'

  #checking for special weather announcement
  weather_alert = ''
  if (soup.find(class_='AlertHeadline--alertText--38xov')):
    weather_alert = soup.find(class_='AlertHeadline--alertText--38xov').text

  #displaying weather information
  print(date_today)
  print(current_temp)
  print(phrase + emoji)
  print("Highest and lowest tempurate of the day: "+temp_hi_lo)

  if pred_phrase != '':
    print(pred_phrase)
  if weather_alert != '':
    print('Weather Alert: !! '+weather_alert+' !!')

  time.sleep(1)

todays_weather()